import { Command } from "commander"
import { privateKeyToAccount } from "viem/accounts"
import type { Address, Hex } from "viem"
import {
  CONTRACTS,
  DEFAULT_RPC_URLS,
  fetchRewardProof,
  fetchValidators,
  findValidator,
  formatDelay,
  formatSafe,
  mockAccount,
  mockSummary,
  mockValidators,
  parseSafeAmount,
  planClaimRewards,
  planClaimWithdrawal,
  planStake,
  planUnstake,
  readAccountSnapshot,
  readHealth,
  readValidatorPositions,
  type TxPlan,
} from "../src/protocol"
import {
  createProductPublicClient,
  output,
  printPlan,
  readPrivateKey,
  resolveRpcUrl,
  sendPlanTransactions,
  writeSafePayloadFile,
  type CliGlobalOptions,
} from "../src/shared/cli"
import { parseAddress, totalAmount } from "../src/shared/utils"

type GlobalOptions = CliGlobalOptions
type WriteOptions = {
  account?: string
  dryRun?: boolean
  send?: boolean
  yes?: boolean
  privateKeyEnv?: string
  safePayload?: string
}

const rpcEnvNames = ["SAFECAFE_RPC_URL", "SAFENET_RPC_URL"] as const
const safePayloadDescription = "Generated by Safecafe CLI. Review every transaction before signing."

const program = new Command()

program
  .name("safecafe")
  .description("Guided non-custodial Safenet staking CLI")
  .version("0.1.0")
  .option("--rpc <url>", "Ethereum RPC URL")
  .option("--json", "Output machine-readable JSON")
  .option("--mock", "Use bundled sample data")
  .showHelpAfterError("(use --help for the Safecafe command menu)")

program
  .command("status")
  .description("Show protocol health and, optionally, one account summary")
  .option("--account <address>", "EOA or Safe address")
  .action(async (options: { account?: string }) => {
    const globals = program.opts<GlobalOptions>()
    if (globals.mock) {
      const payload = {
        mode: "mock",
        account: options.account ?? mockAccount,
        health: { rpc: "healthy", blockNumber: 19234221n, merkleRoot: "matched" },
        summary: mockSummary,
      }
      output(globals, payload, () => {
        console.log("Safecafe is ready")
        console.log(`Account:               ${payload.account}`)
        console.log(`SAFE balance:          ${formatSafe(mockSummary.safeBalance)}`)
        console.log(`Total staked:          ${formatSafe(mockSummary.totalStaked)}`)
        console.log(`Claimable rewards:     ${formatSafe(mockSummary.claimableRewards)}`)
        console.log(`Claimable withdrawals: ${formatSafe(mockSummary.claimableWithdrawals)}`)
      })
      return
    }

    const client = createClient(globals)
    const health = await readHealth(client)
    const account = options.account ? parseAddress(options.account, "account") : undefined
    const snapshot = account ? await readAccountSnapshot(client, account) : null
    output(globals, { health, account, snapshot }, () => {
      console.log("Safecafe protocol check")
      console.log(`RPC:              healthy`)
      console.log(`Block:            ${health.blockNumber}`)
      console.log(`Withdrawal delay: ${formatDelay(health.withdrawDelay)}`)
      console.log(`Merkle root:      ${health.merkleRoot}`)
      if (account && snapshot) {
        console.log("")
        console.log(`Account:          ${account}`)
        console.log(`SAFE balance:     ${formatSafe(snapshot.safeBalance)}`)
        console.log(`Total staked:     ${formatSafe(snapshot.totalStaked)}`)
        console.log(`Pending queue:    ${formatSafe(totalAmount(snapshot.pendingWithdrawals))}`)
      }
    })
  })

program
  .command("menu")
  .description("Browse validators like a staking menu")
  .option("--active", "Only show active validators")
  .option("--sort <field>", "Sort by name, participation, commission, or stake", "participation")
  .action(async (options: { active?: boolean; sort: string }) => {
    const globals = program.opts<GlobalOptions>()
    const validators = globals.mock ? mockValidators : await fetchValidators()
    const filtered = validators
      .filter((validator) => !options.active || validator.status === "active")
      .sort((a, b) => {
        if (options.sort === "name") return a.label.localeCompare(b.label)
        if (options.sort === "commission") return a.commission - b.commission
        if (options.sort === "stake") return Number(b.totalStake - a.totalStake)
        return b.participationRate - a.participationRate
      })

    output(globals, filtered, () => {
      console.log("Validator menu")
      for (const validator of filtered) {
        console.log(
          `${validator.label.padEnd(22)} ${validator.status.padEnd(8)} participation ${validator.participationRate
            .toFixed(1)
            .padStart(6)}%  fee ${validator.commission.toFixed(1).padStart(5)}%  stake ${formatSafe(validator.totalStake)}`,
        )
      }
    })
  })

program
  .command("brew")
  .description("Plan or send a stake transaction")
  .requiredOption("--validator <address-or-name>", "Validator address or known label")
  .requiredOption("--amount <safe>", "SAFE amount")
  .option("--account <address>", "Account used for planning")
  .option("--dry-run", "Only print the transaction plan", true)
  .option("--safe-payload <path>", "Write a Safe Transaction Builder JSON payload")
  .option("--send", "Send transactions with a local private key")
  .option("--private-key-env <name>", "Environment variable containing private key")
  .option("--yes", "Confirm live transaction sending")
  .action(async (options: WriteOptions & { validator: string; amount: string }) => {
    const globals = program.opts<GlobalOptions>()
    const validator = await resolveValidator(options.validator, globals.mock)
    const account = resolvePlanningAccount(options, globals)
    const allowance = globals.mock || !account ? 0n : (await readAccountSnapshot(createClient(globals), account)).stakingAllowance
    if (!globals.mock && account) await assertStakePossible(globals, account, validator, options.amount)
    await handlePlan(globals, planStake({ validator, amount: options.amount, account, allowance }), options)
  })

program
  .command("cool")
  .description("Plan or send an unstake transaction")
  .requiredOption("--validator <address-or-name>", "Validator address or known label")
  .requiredOption("--amount <safe>", "SAFE amount")
  .option("--account <address>", "Account used for planning")
  .option("--dry-run", "Only print the transaction plan", true)
  .option("--safe-payload <path>", "Write a Safe Transaction Builder JSON payload")
  .option("--send", "Send transactions with a local private key")
  .option("--private-key-env <name>", "Environment variable containing private key")
  .option("--yes", "Confirm live transaction sending")
  .action(async (options: WriteOptions & { validator: string; amount: string }) => {
    const globals = program.opts<GlobalOptions>()
    const validator = await resolveValidator(options.validator, globals.mock)
    const account = resolvePlanningAccount(options, globals)
    if (!globals.mock && account) await assertUnstakePossible(globals, account, validator, options.amount)
    await handlePlan(globals, planUnstake({ validator, amount: options.amount, account }), options)
  })

program
  .command("tab")
  .description("Show withdrawal queue for an account")
  .requiredOption("--account <address>", "EOA or Safe address")
  .action(async (options: { account: string }) => {
    const globals = program.opts<GlobalOptions>()
    if (globals.mock) {
      output(globals, mockSummary, () => {
        console.log(`Pending withdrawal tab: ${formatSafe(mockSummary.pendingWithdrawals)} SAFE`)
        console.log(`Ready to collect:       ${formatSafe(mockSummary.claimableWithdrawals)} SAFE`)
        console.log(`Protocol delay:         ${formatDelay(mockSummary.withdrawDelay)}`)
      })
      return
    }

    const account = parseAddress(options.account, "account")
    const snapshot = await readAccountSnapshot(createClient(globals), account)
    output(globals, snapshot.pendingWithdrawals, () => {
      if (!snapshot.pendingWithdrawals.length) {
        console.log("No withdrawal tab is open.")
        return
      }
      snapshot.pendingWithdrawals.forEach((withdrawal, index) => {
        const date = new Date(Number(withdrawal.claimableAt) * 1000).toISOString()
        console.log(`#${index + 1} ${formatSafe(withdrawal.amount)} SAFE ready at ${date}`)
      })
    })
  })

program
  .command("collect-withdrawal")
  .description("Plan or send a withdrawal claim")
  .option("--account <address>", "Account used for planning")
  .option("--dry-run", "Only print the transaction plan", true)
  .option("--safe-payload <path>", "Write a Safe Transaction Builder JSON payload")
  .option("--send", "Send transactions with a local private key")
  .option("--private-key-env <name>", "Environment variable containing private key")
  .option("--yes", "Confirm live transaction sending")
  .action(async (options: WriteOptions) => {
    const globals = program.opts<GlobalOptions>()
    const account = resolvePlanningAccount(options, globals)
    if (!globals.mock && account) await assertWithdrawalClaimable(globals, account)
    await handlePlan(globals, planClaimWithdrawal(account), options)
  })

program
  .command("beans")
  .description("Show reward proof and claimable reward status")
  .requiredOption("--account <address>", "EOA or Safe address")
  .action(async (options: { account: string }) => {
    const globals = program.opts<GlobalOptions>()
    if (globals.mock) {
      output(globals, { account: options.account, claimable: mockSummary.claimableRewards }, () => {
        console.log(`Account:          ${options.account}`)
        console.log(`Reward beans:     ${formatSafe(mockSummary.claimableRewards)} SAFE`)
        console.log("Proof status:     sample data")
      })
      return
    }

    const account = parseAddress(options.account, "account")
    const [proof, snapshot, health] = await Promise.all([
      fetchRewardProof(account),
      readAccountSnapshot(createClient(globals), account),
      readHealth(createClient(globals)),
    ])
    const cumulativeAmount = proof ? BigInt(proof.cumulativeAmount) : 0n
    const claimable = cumulativeAmount > snapshot.cumulativeClaimed ? cumulativeAmount - snapshot.cumulativeClaimed : 0n
    const rootMatched = proof ? proof.merkleRoot.toLowerCase() === health.merkleRoot.toLowerCase() : false
    output(globals, { account, proofFound: !!proof, rootMatched, claimable, proof }, () => {
      console.log(`Account:      ${account}`)
      console.log(`Proof found:  ${proof ? "yes" : "no"}`)
      console.log(`Claimable:    ${formatSafe(claimable)} SAFE`)
      if (proof) console.log(`Root matched: ${rootMatched ? "yes" : "no"}`)
    })
  })

program
  .command("collect-rewards")
  .description("Plan or send a reward claim")
  .requiredOption("--account <address>", "Reward account")
  .option("--dry-run", "Only print the transaction plan", true)
  .option("--safe-payload <path>", "Write a Safe Transaction Builder JSON payload")
  .option("--send", "Send transactions with a local private key")
  .option("--private-key-env <name>", "Environment variable containing private key")
  .option("--yes", "Confirm live transaction sending")
  .action(async (options: WriteOptions & { account: string }) => {
    const globals = program.opts<GlobalOptions>()
    const account = parseAddress(options.account, "account")
    if (globals.mock) {
      await handlePlan(
        globals,
        planClaimRewards({
          account,
          cumulativeAmount: mockSummary.claimableRewards,
          merkleRoot: `0x${"0".repeat(64)}` as Hex,
          proof: [],
        }),
        options,
      )
      return
    }
    await assertRewardsClaimable(globals, account)
    const proof = await fetchRewardProof(account)
    if (!proof || !proof.proof) throw new Error("No claimable proof found for account")
    await handlePlan(
      globals,
      planClaimRewards({
        account,
        cumulativeAmount: BigInt(proof.cumulativeAmount),
        merkleRoot: proof.merkleRoot,
        proof: proof.proof,
      }),
      options,
    )
  })

program
  .command("contracts")
  .description("Print contract addresses")
  .action(() => {
    const globals = program.opts<GlobalOptions>()
    output(globals, CONTRACTS, () => {
      console.log(`SAFE token:        ${CONTRACTS.safeToken}`)
      console.log(`Staking contract:  ${CONTRACTS.staking}`)
      console.log(`Rewards contract:  ${CONTRACTS.merkleDrop}`)
      console.log(`Multicall3:        ${CONTRACTS.multicall3}`)
    })
  })

program
  .command("guide")
  .description("Print the Safecafe guided workflow")
  .action(() => {
    console.log("Safecafe guided flow")
    console.log("")
    console.log("1. Check the protocol and your account")
    console.log("   safecafe status --account 0xYourSafe")
    console.log("")
    console.log("2. Pick a validator")
    console.log("   safecafe menu --active --sort participation")
    console.log("")
    console.log("3. Prepare a stake")
    console.log('   safecafe brew --account 0xYourSafe --validator "Core Contributors" --amount 100 --dry-run')
    console.log("")
    console.log("4. Export a Safe payload")
    console.log('   safecafe brew --account 0xYourSafe --validator "Core Contributors" --amount 100 --safe-payload ./safecafe-safe.json')
    console.log("")
    console.log("5. Collect rewards when proof is available")
    console.log("   safecafe beans --account 0xYourSafe")
  })

program.parseAsync(process.argv).catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})

function createClient(globals: GlobalOptions) {
  return createProductPublicClient(globals, process.env, rpcEnvNames)
}

function resolvePlanningAccount(options: WriteOptions, globals: GlobalOptions): Address | undefined {
  if (globals.mock) return undefined
  if (options.account) return parseAddress(options.account, "account")
  if (options.send) return privateKeyToAccount(readPrivateKey(options.privateKeyEnv, process.env)).address
  throw new Error("--account is required for live planning. Use --send with --private-key-env for EOA sending.")
}

async function resolveValidator(query: string, mock?: boolean): Promise<Address> {
  const direct = tryParseAddress(query)
  if (direct) return direct
  const validators = mock ? mockValidators : await fetchValidators()
  const validator = findValidator(validators, query)
  if (!validator) throw new Error(`Unknown validator: ${query}`)
  return validator.address
}

function tryParseAddress(value: string): Address | null {
  try {
    return parseAddress(value)
  } catch {
    return null
  }
}

async function assertStakePossible(globals: GlobalOptions, account: Address, validator: Address, amountText: string) {
  const amount = parseSafeAmount(amountText)
  const client = createClient(globals)
  const [snapshot, validators] = await Promise.all([
    readAccountSnapshot(client, account),
    fetchValidators(),
  ])
  const validatorMetadata = findValidator(validators, validator)
  if (validatorMetadata?.status === "inactive") throw new Error(`Validator is inactive: ${validatorMetadata.label}`)
  if (snapshot.safeBalance < amount) {
    throw new Error(`Insufficient SAFE balance. Need ${formatSafe(amount)}, have ${formatSafe(snapshot.safeBalance)}.`)
  }
}

async function assertUnstakePossible(globals: GlobalOptions, account: Address, validator: Address, amountText: string) {
  const amount = parseSafeAmount(amountText)
  const [position] = await readValidatorPositions(createClient(globals), account, [
    {
      address: validator,
      label: "Selected validator",
      status: "active",
      commission: 0,
      participationRate: 0,
      totalStake: 0n,
      userStake: 0n,
    },
  ])
  if (position.userStake < amount) {
    throw new Error(`Insufficient validator stake. Need ${formatSafe(amount)}, have ${formatSafe(position.userStake)}.`)
  }
}

async function assertWithdrawalClaimable(globals: GlobalOptions, account: Address) {
  const snapshot = await readAccountSnapshot(createClient(globals), account)
  const [amount, claimableAt] = snapshot.nextClaimableWithdrawal
  const now = BigInt(Math.floor(Date.now() / 1000))
  if (amount <= 0n || claimableAt > now) {
    const suffix = claimableAt > 0n ? ` Next claimable at ${new Date(Number(claimableAt) * 1000).toISOString()}.` : ""
    throw new Error(`No withdrawal is claimable yet.${suffix}`)
  }
}

async function assertRewardsClaimable(globals: GlobalOptions, account: Address) {
  const client = createClient(globals)
  const [proof, snapshot, health] = await Promise.all([
    fetchRewardProof(account),
    readAccountSnapshot(client, account),
    readHealth(client),
  ])
  if (!proof || !proof.proof) throw new Error("No reward proof found for account.")
  if (proof.merkleRoot.toLowerCase() !== health.merkleRoot.toLowerCase()) throw new Error("Reward proof Merkle root does not match the live contract root.")
  const cumulativeAmount = BigInt(proof.cumulativeAmount)
  if (cumulativeAmount <= snapshot.cumulativeClaimed) throw new Error("Rewards are already fully claimed.")
}

async function handlePlan(globals: GlobalOptions, plan: TxPlan, options: WriteOptions) {
  if (globals.mock && options.send) throw new Error("--mock cannot be combined with --send")

  if (options.safePayload) {
    const payload = writeSafePayloadFile(plan, options.safePayload, safePayloadDescription)
    if (globals.json) {
      output(globals, payload, () => undefined)
      return
    }
    printPlan(plan)
    console.log("")
    console.log(`Safe Transaction Builder payload written to ${options.safePayload}`)
    return
  }

  output(globals, plan, () => printPlan(plan))

  if (!options.send) return
  if (!options.yes) throw new Error("--yes is required with --send to confirm live transaction submission")

  await sendPlanTransactions(plan, {
    privateKey: readPrivateKey(options.privateKeyEnv, process.env),
    rpcUrl: resolveRpcUrl(globals, process.env, rpcEnvNames) || DEFAULT_RPC_URLS[0],
    onSubmitted: (label, hash) => console.log(`Submitted ${label}: ${hash}`),
    onConfirmed: (label, blockNumber) => console.log(`Confirmed ${label}: block ${blockNumber}`),
  })
}
